### ISSUE TITLE
.pem file Not Found

### ISSUE THREAD

**Issue by nfbalbontin** [iic2173/2019-02#10]
Hola! qué tal? 
Dentro de AWS cree una nueva instancia tal como en la ayudantía, ingreso mediante ssh y al momento de copiar mi key al servidor me aparece como error: 
`cp: cannot stat 'chat.pem': No such file or directory`
Con esto quise ver si se encontraba el archivo, por lo que ejecuté: 
` ls ~/.ssh`
Lo que me entregó: 
`authorized_keys`
Lo que encontré raro ya que debería decirme mi archivo `.pem`.
A partir de esto busqué errores similares y encontré: https://unix.stackexchange.com/questions/172385/cp-cannot-stat-no-such-file-or-directory
Seguí los pasos indicados y aún así no logro copiar el archivo al servidor. 
¿Es necesario alguna configuración en particular de la instancia para poder generar la copia?

**Comment by elramirezv123** [comment]
Hola!

¿Por qué quieres copiar el archivo `.pem` al servidor? Si ya pudiste conectarte mediante `ssh` no debería de ser necesario.

**Comment by nfbalbontin** [comment]
Era uno de los pasos de la ayudantía. ¿No es necesario?

**Comment by nacosta-cl** [comment]
Hola!
La llave ```.pem``` solo la posee el cliente (o sea tu) y es privada. No debe ser enviada al servidor, pues este ya tiene la clave publica que necesita para conectarse. El cliente ssh usa la llave para conectarse, sea ssh nativo o putty.
Debes dejar la llave que AWS (o gcloud) te entrego en el home de linux, en la carpeta ```.ssh``` y dejarle los permisos apropiados (```chmod 400``` si mal no recuerdo)

```authorized_keys``` tiene que ver con otros conceptos de ssh y para esta entrega no es necesario modificar este archivo

**Comment by nfbalbontin** [comment]
gracias!
