### ISSUE TITLE
Problema conexión remota a nginx web server

### ISSUE THREAD

**Issue by mframos3** [iic2173/2019-02#11]
Hola, siguiendo los pasos de la instalación de Nginx del enunciado de la entrega [https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-18-04-quickstart](), me encuentro con un problema en el paso 3: Checking your Web Server. 

No me puedo conectar usando la dirección IP de la máquina para llegar a la landing page de Nginx. Se puede ver que al ejecutar `systemctl status nginx` al levantarse el server sale un mensaje de error  `nginx.service: Failed to read PID from file /run/nginx.pid`. Solucioné este problema pero aun así no puedo conectarme (no sé si tiene relación).

**Comment by elramirezv123** [comment]
Hola!

Puedes subir una foto del grupo de seguridad de tu instancia? Puede ser que no hayas habilitado el puerto 80 para las conexiones HTTP y por eso no te muestra nada

**Comment by mframos3** [comment]
Gracias! Ya lo pude solucionar.
