### ISSUE TITLE
conexion https

### ISSUE THREAD

**Issue by nissimergas** [iic2173/2019-02#12]
Alguna idea porque me puede estar quedando esto asi?
![image](https://user-images.githubusercontent.com/18380055/63980182-d6d29a00-ca88-11e9-9558-c684af7142f7.png)

**Comment by nacosta-cl** [comment]
El certificado de tu sitio esta emitido para una IP, y no para el nombre de dominio especifico. Además, parece que lo emitiste tu mismo, y no a través de un emisor de certificados, como Let's Encrypt, lo cual hace que Chrome de la alarma.

Suerte!
