### ISSUE TITLE
Websockets + Nginx + Gunicorn

### ISSUE THREAD

**Issue by FernandoPieressa** [iic2173/2019-02#13]
Hola!

Estoy intentando implementar websockets con la librería socketIO con Nginx, sin embargo al hacer el deploy de la aplicación recibo errores 404 (Bad Request) por parte de la librería. Tengo configurado Nginx con las variables escritas en este link https://chrislea.com/2013/02/23/proxying-websockets-with-nginx/

pero no logro hacerlo funcionar. Alguien sabe cual podría ser el problema?

**Comment by JorgeBdelaT** [comment]
Hola, pudiste resolver el problema? a mi me pasa lo mismo :(

**Comment by FranciscoLarach** [comment]
A mi me pasa lo mismo pero con (redis_)channels al hacerlo con Django, por si alguien pudo solucionarlo.

**Comment by nissimergas** [comment]
Hola,
a mi me pasaba lo mismo,
 lo arregle cambiando el comando
 gunicorn3 app:app
 por
 gunicorn3 --worker-class eventlet -w 1 app:app
Si  es que no les funciona eso deberían revisar que estén usando la direccion correcta del socket por el lado del cliente. 
ponerlo asi debería hacer que funcione:
  ```var socket = io.connect('https://' + document.domain) // + ':' + location.port);```

**Comment by FernandoPieressa** [comment]
Respecto a
var socket = io.connect('https://' + document.domain) // + ':' + location.port);
Si usas http normal no te funciona?

Porque yo lo tengo asi y tiene el mismo error. Tu usaste la misma confirguracion de nginx del link que mostre arriba?

**Comment by nissimergas** [comment]
si lo tienen sin https te funciona con http

**Comment by nissimergas** [comment]
No use lo mismo...
El mio se parece más al que sale acá: https://flask-socketio.readthedocs.io/en/latest/
Probablemente te falta meter esto en el server:
```
  location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:<insertar puerto>/socket.io;
    }
```

**Comment by nissimergas** [comment]
también revisa que estes usando los puertos correctos...

**Comment by FernandoPieressa** [comment]
Era un problema de cors.

Resuelto!
