### ISSUE TITLE
Tipo de chat pedido

### ISSUE THREAD

**Issue by bamavrakis** [iic2173/2019-02#14]
Hola!

Tengo una duda sobre el tipo de chat que hay que implementar:
- Es un único "channel" en donde todos los usuarios pueden escribir.
- Es un chat 1 a 1, en donde se tienen todos los miembros conectados, y al seleccionar alguno se abre un chat privado.

Saludos!

**Comment by elramirezv123** [comment]
Hola!

La primera opción. Es un único channel donde todos pueden escribir.
