### ISSUE TITLE
IP shows Django vs Domain  shows Nginx

### ISSUE THREAD

**Issue by ofvera** [iic2173/2019-02#16]
Luego de terminar la guía para montar la app de django con postgres, nginx y gunicorn, al ingresar al IP de mi servidor efectivamente puedo ver la app de django, sin embargo al ingresar al dominio el IP me rechaza la conexión. 
Si hago un cambio en el archivo ubicado en `/etc/nginx/sites-available` cambiando el server_name que tiene el IP al del dominio ambos me muestran la página de nginx. 
Por otra parte, el archivo `settings.py`, recibe en allowed_hosts tanto el IP como los dominios validos, por lo que descarto que ese sea el problema.
Alguna idea de que puede ser? En todos lados me dice que debe ser el archivo ubicado en `/etc/nginx/sites-available` pero aún editandolo no logro nada.

**Comment by nachocontreras** [comment]
Probaste colocando en el archivo:
server_name example.com www.example.com; 
??

**Comment by miguelramirezv** [comment]
Hola a mi me pasa lo mismo y sí agregué el server_name example.com www.example.com; Pero ahora no se me carga la página. También usé Django y gunicorn

**Comment by elramirezv123** [comment]
@ofvera probaste con eliminar el archivo en `/etc/nginx/sites-enabled` y generar uno nuevo?  Hay veces que nginx se queda con la versión "anterior".

Para eliminarlo debes hacerlo con el usuario `root`, para ello debes ejecutar el comando: `sudo - su` y luego para volver a la sesión `ubuntu`. Para desconectarte de `root`, correr: `logout `

**Comment by mraddatz** [comment]
Que guía usaron para esto?

**Comment by ofvera** [comment]
He hecho todo eso y no funciona aún, yo creo que empezaré de cero la guía por que es extraño el problema. 
`Que guía usaron para esto?`
Digital Ocean
https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-18-04
