### ISSUE TITLE
Problema con Let's Encrypt Cerbot 

### ISSUE THREAD

**Issue by nfbalbontin** [iic2173/2019-02#17]
Hola, qué tal? 
Instalé Let's Encrypt Cerbot para poder tener mi dominio asegurado por SSL.
Para que funcionara, agregué el puerto necesario para la conexión tanto en mi servidor en AWS como en el firewall. El problema es que luego de instalarlo y habilitar los puertos se pierde la conexión con el servidor. A partir de esto revisé los archivos creados para ver si se habían generado incongruencias, por lo que el primer archivo que revisé fue: 
`/etc/nginx/sites-available/myproject`
Al que se le había agregado tanto la definición de un servidor como la siguiente codificación:
<img width="621" alt="Captura de Pantalla 2019-09-03 a la(s) 18 08 59" src="https://user-images.githubusercontent.com/26261777/64211999-fa755600-ce75-11e9-87a9-ba07acaca4f1.png">
Al eliminar la carpeta de "letsencrypt", borrar ese segmento de código del servidor y agregar a la definición original del servidor nuevamente el parámetro "listen" - que no entiendo por qué al descagar letsencrypt este lo elimina - el servidor restablece su conexión PERO solamente en navegación incógnita y obviamente sin lograr asegurar mi dominio. 
Busqué en internet algunas posibles solciones y entre estas estaba habilitar los puertos http y https, cosa que aún no hace que funcione. 
Yo creo que el problema se debe generar debido a un bloqueo del firewall, lo extraño es que se caiga la conexión completa y al habilitar el puerto necesario aún así no habilite la conexión. ¿Qué otro tipo de bloqueos por parte del firewall puede estar generándose al integrar letsencrypt que no me permita la conexión con el servidor? 

Gracias

**Comment by mframos3** [comment]
También me ocurre que previo a instalar los certificados la aplicación funcionaba. Ahora instalé los certificados, abrí los puertos 80 y 443 para HTTP y HTTPS, probe distintas configs de Nginx y entregue como parámetros a mi server el certificado y key .pem. 

Corro el script del servidor posterior a agregarle los parámetros key y certificate sin tirar error.
Supongo también que hay algo que no permite el acceso remoto.

**Comment by mframos3** [comment]
@nfbalbontin Para solucionarlo ejecuté el comando `ufw allow https` y funcionó. Respecto a mi comentario de que agregué parametros key y certificado en mi server.js, al final los tuve que remover para que la app funcione.
Ojalá te ayude
