### ISSUE TITLE
Últimos 100 mensajes en páginas de a 5 mensajes

### ISSUE THREAD

**Issue by tommyefr** [iic2173/2019-02#2]
En el enunciado se menciona que '*Se debe poder ver los últimos 100 mensajes enviados en páginas de 5 mensajes cada una*'.  Me surgen la siguientes dudas:

1. ¿Esto significa que se debe presentar una vista con solo 5 mensajes y luego dar la opción de mostrar los siguientes 5, perso sin mostrar los anteriores?

2. ¿Estos 100 mensajes deben persistir de alguna forma si el usuario se desconecta de la aplicación y luego se vuelve a conectar o son los útlimos 100 mensajes de la sesión actual?

**Comment by nacosta-cl** [comment]
1.- Claro, la intencion es lograr algo asi [https://getbootstrap.com/docs/4.3/components/pagination/](url)

2.- Piensalo como un panel libre donde cualquiera puede escribir, como un tablon de anuncios muy simple.

**Comment by NachoCasta** [comment]
Tienen que ser exactamente los últimos 100? O puedo mostrar todos los mensajes aunque sean más de 100?

**Comment by elramirezv123** [comment]
Pueden ser más, lo importante es que estén paginados.

**Comment by DiegoAndai** [comment]
@nacosta-cl sobre el punto 2 de tu respuesta original, ¿entonces no es necesario que los nuevos mensajes lleguen sin recargar la página? Pregunto esto pues es un chat, entonces asumí que tenía live updates y por lo tanto necesitaría un socket, pero pensando en un tablero de anuncios quizás esto no es necesario.
