### ISSUE TITLE
Con respecto a los últimos 100 mensajes

### ISSUE THREAD

**Issue by arpincheira** [iic2173/2019-02#20]
Hola, tenía una duda con respecto a eso de que se deben mostrar los últimos 100 mensajes en páginas de 5. Con esto se refiere a que solo se deben mostrar los últimos 100  o es **por lo menos 100**(me refiero a que si hay 110 mensajes que se puedan ver los 110).

Muchas gracias de antemano

**Comment by nacosta-cl** [comment]
Evaluaremos que se puedan ver al menos 100
Si quieres implementar mas, no hay problema, pero tiene que poder cumplirse el primer criterio

Suerte!
