### ISSUE TITLE
[E0] Problema con carga de HTTPS

### ISSUE THREAD

**Issue by miguelramirezv** [iic2173/2019-02#21]
Hola! Yo desarrollé mi página con Django y luego la deployee con Gunicorn y Nginx. Luego usé mi dominio de Freenom y hasta ahí casi todo bien. Podía ver y usar bien mi página cuando me metía al IP, pero en el dominio me salía la página básica de Nginx.

No sabía bien como solucionarlo pero seguí desarrollando lo último que me faltaba hacer que era el SSL, que lo realicé con este tutorial: 
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
Ahí puede realizar todo bien y sin errores como se verifica en el último paso. Sin embargo, ahora cuando cargo mi dominio que se redirige siempre a HTTPS, no se me carga mi aplicación, ni siquiera un simple texto de html. Al abrir la consola me sale el siguiente error: 
"Failed to load resource: bad URL"

Bueno ante este problema he estado buscando muchas soluciones en internet como en otras issues, pero todos lo que recomiendan hacer no me ha servido. Las soluciones principales que he intentado usar han sido:
- agregar "server_name example.com www.example.com;" lo que hice en el tutorial
- ejecutar el comando "ufw allow https"
- agregar "SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')" y 
"location / {
     ... 
    proxy_set_header X-Forwarded-Proto $scheme;
}"

Sin embargo mi dominio sigue sin cargar ni funcionar con HTTPS, mientras que mi dirección IP sí funciona con HTTP y no funciona con HTTPS.

Saben alguna causa o solución a esto?

Muchas gracias!!

**Comment by lechodiman** [comment]
Revisaste que esté abierto el puerto para https en inbound rules de tu instancia EC2? A mi me pasó eso que dices tú y era solo abrir el puerto en aws 😀

**Comment by miguelramirezv** [comment]
Eso era! Muchas gracias!! Ahora tengo el problema que la página que me muestra en mi dominio es la básica de Nginx y no es mi aplicación, mientras que en mi IP se ve y funciona mi aplicación. Esto por qué será?

**Comment by lechodiman** [comment]
Eso puede ser porque lo tengas configurado así en tu archivo de configuración en `/conf.d/` o en `/sites-enabled/ `o donde sea que estés configurando a nginx.  Revisa qué tienes en la configuración server_name

**Comment by miguelramirezv** [comment]
Tenía puesto el IP, ahora lo cambié a mi dominio pero ahora no se me carga nada en el IP, y en el dominio me sigue cargando la página básica. No sé porque pasa eso.

**Comment by miguelramirezv** [comment]
Era que había que cambiar el default también! Gracias!!
