### ISSUE TITLE
usuario anónimo

### ISSUE THREAD

**Issue by movaldivia** [iic2173/2019-02#23]
Hola!

En el enunciado del proyecto 0 leí que a los usuarios se les debía dar un nickname anónimo temporal. Luego, leyendo las puntuaciones no se menciona esta feature. 

¿Es necesario entregar un nickname al usuario?

**Comment by elramirezv123** [comment]
Hola!

Si, la idea es que tenga un nickname, pero no será tan relevante en el puntaje.

**Comment by movaldivia** [comment]
@elramirezv123  vale gracias !
