### ISSUE TITLE
Sobre archivo .pem

### ISSUE THREAD

**Issue by abannura** [iic2173/2019-02#27]
Al crear un nuevo par de llaves me surgió una duda respecto a cómo funciona el sistema de autenticación de AWS.

No entiendo porque hay que registrar manualmente la public key que acabo pedir, en el archivo "authorized_keys" del servidor.

No debería AWS registrar esa key automáticamente en el servidor? Tal y como hizo con el par inicial de keys que uno crea cuando lanza la instancia EC2?

Tampoco entiendo porque la consola de AWS guarda registro de que pares de llave he solicitado. Qué ocurre si elimino la llave desde la consola? Dado que registre manualmente la llave en el servidor, esta debería seguir vigente o no? A pesar de que ya no este en la consola de AWS.

Saludos

**Comment by nacosta-cl** [comment]
Basicamente, AWS te da acceso a los servidores mediante SSH. Puedes encontrar mas informacion detallada acerca del funcionamiento especifico de SSH en 
* El libro "SSH, The Secure Shell: The Definitive Guide" 
* https://en.wikipedia.org/wiki/Secure_Shell

Authorized keys contiene las llaves publicas que autorizaste para tu usuario. 
AWS solo registra una llave inicial para poder entrar al servidor (de otro modo no tendrias como entrar). Si quieres emitir mas llaves que no sean de lanzamiento, es un proceso que debes hacer tu mismo.

AWS y en general cualquier proveedor de servicios en la nube solo guarda la llave pública del par de llaves. Si la borras de la **consola de AWS** solo dejara de estar disponible para futuros lanzamientos, ellos dejan de tenerla, pero podras seguir conectandote a tu instancia (no es que la borren de tu servidor). Aqui puedes encontrar mas info de como manejan las llaves
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html

**Comment by nacosta-cl** [comment]
Basicamente, AWS te da acceso a los servidores mediante SSH. Puedes encontrar mas informacion detallada acerca del funcionamiento especifico de SSH en 
* El libro "SSH, The Secure Shell: The Definitive Guide" 
* https://en.wikipedia.org/wiki/Secure_Shell

Authorized keys contiene las llaves publicas que autorizaste para tu usuario. 
AWS solo registra una llave inicial para poder entrar al servidor (de otro modo no tendrias como entrar). Si quieres emitir mas llaves que no sean de lanzamiento, es un proceso que debes hacer tu mismo.

AWS y en general cualquier proveedor de servicios en la nube solo guarda la llave pública del par de llaves. Si la borras de la **consola de AWS** solo dejara de estar disponible para futuros lanzamientos, ellos dejan de tenerla, pero podras seguir conectandote a tu instancia (no es que la borren de tu servidor). Aqui puedes encontrar mas info de como manejan las llaves
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html
