### ISSUE TITLE
Cantidad de interrogaciones

### ISSUE THREAD

**Issue by DiegoAndai** [iic2173/2019-02#29]
Hola! creo que encontré un error en el programa del curso:

<img width="802" alt="Captura de Pantalla 2019-09-07 a la(s) 02 07 30" src="https://user-images.githubusercontent.com/16889233/64470622-6c6acb00-d114-11e9-9961-32bf11b5d713.png">

Dice que habrá 3 interrogaciones pero en las fechas y cálculo de nota se consideran solo dos, ¿qué es lo correcto?

**Comment by elramirezv123** [comment]
Hola!

Disculpa la demora, son solo 2 interrogaciones.

**Comment by DiegoAndai** [comment]
Gracias!
