### ISSUE TITLE
Indicaciones para crear AWS

### ISSUE THREAD

**Issue by tmorales1** [iic2173/2019-02#3]
Con indicaciones para hacer la entrega0 (crear AWS y otros) se refieren a los links que ponen cómo relevantes en el enunciado? En caso de ser así se espera que leamos todo el material o algunos enlaces específicos son más indispensables que otros? 

Si no es se refiere a estos enlaces, a que se refiere "Les daremos indicaciones de como crear un servidor en AWS y montar su aplicacion".

Saludos

**Comment by nacosta-cl** [comment]
Los links que proporcionamos son lectura de apoyo.
Este viernes les daremos la base para trabajar en la tarea y que puedan crear su servidor en AWS

**Comment by nacosta-cl** [comment]
Acabo de subir una guia sobre la creacion de la cuenta educacional (u obtencion de los creditos educacionales.
