### ISSUE TITLE
Integration continua

### ISSUE THREAD

**Issue by FernandoPieressa** [iic2173/2019-02#34]
Hola!

Tengo unas dudas respecto a que se espera con integración continua específicamente (que tanto se debe usar, en que partes de todo el sistema,  etc..), debido a que tanto en CircleCI como TravisCI, este es compartido por organización y no por repositorio, por lo que al ser 80 alumnos estos pueden colapsar.

En caso de CircleCI, la version gratis cuenta con una cantidad maxima de tests por periodo que se agotara rápido.

En caso de TravisCI, que con la version que se puede usar de GitHub education se tiene 1 worker por organización, por lo que en periodos cercanos a entregas va a ser muy difícil de utilizar asumiendo que todos los grupos harán sus push cercana a la hora de entrega.

Estas herramientas solo pueden ser agregadas por owners de la organizacion por lo que queria saber si las pueden añadir para poder trabajar

Tambien queria saber que se espera que testemos, solo la aplicacion de steam? los juegos tambien?

Muchas gracias!

**Comment by FernandoPieressa** [comment]
@nacosta-cl

**Comment by naquiroz** [comment]
Compartieron los repositorios por slack, pero me sumo a la duda de lo de CI
