### ISSUE TITLE
conexión ssh

### ISSUE THREAD

**Issue by hrhartmann** [iic2173/2019-02#4]
Una vez que guardé la clave en ssh (putty gen) y luego le hice match con el ip, como me conecto al servidor ?? escribo ssh myusername@myip y me aparece:
Permission denied (publickey).

**Comment by elramirezv123** [comment]
Hola!

Probaste con **ubuntu** en vez de **myusername** como usuario ?

Yo no tengo Windows, asique no trabajo con PuTTY, pero se me hace la idea de que puede ser lo primero que dije, o porque no se le están dando los permisos necesarios al `.pem` para ser utilizados.
Encontré este tutorial que quizás te podría servir: https://www2.linuxacademy.com/howtoguides/17385-use-putty-to-access-ec2-linux-instances-via-ssh-from-windows/

Por otro lado, me parece que en la Windows PowerShell funciona el comando `ssh` para conectarse directamente al servidor, o también en la [Linux Bash](https://itsfoss.com/install-bash-on-windows/) que existe para Windows.

Para poder conectarte basta:
```
sudo chmod 600 nombrekey.pem
ssh -i nombrekey.pem ubuntu@my-ip
```

**Comment by hrhartmann** [comment]
Buena!! parece que me funcionó !! Muchas graciass
