### ISSUE TITLE
Problemas en la creación de cuenta AWS

### ISSUE THREAD

**Issue by Polea012** [iic2173/2019-02#5]
Al crear mi cuenta personal AWS estoy recibiendo errores porque no se está reconociendo mi tarjeta MACH como método de pago en la inscripción, a pesar de que la tarjeta si queda registrada en la cuenta. Debido a esto no tengo acceso a las herramientas necesarias para crear el servidor.

He colocado en reiteradas ocasiones la tarjeta asegurándome que están todos los datos correctos (como indiqué antes, la tarjeta es guardada en la cuenta). Pero aún así me dice que hay un error con la información de pago.

Qué puedo hacer en este caso? Hay alguien que haya tenido este problema también?

Saludos.

**Comment by elramirezv123** [comment]
Si es que el problema persiste, podrías utilizar [Digital Ocean](https://cloud.digitalocean.com) para no tener problemas de tiempo con la E0 (El servicio es básicamente lo mismo). Además, con la cuenta de GitHub te regalan 50USD para lo que quieras.
