### ISSUE TITLE
Usos de otros IaaS y otros dominios

### ISSUE THREAD

**Issue by FarDust** [iic2173/2019-02#6]
Saludos, me preguntaba 3 cosas.
- Si es posible usar otro IaaS como Google Cloud para el desarrollo de la entrega.
- Es posible usar algún PaaS con free tier que permita configurar el proxy inverso con Nginx.
- Es posible usar un dominio que ya tengo comprado para mis proyectos personales en vez de los dominios descritos en el enunciado de la entrega.

**Comment by elramirezv123** [comment]
Hola!

1. Cualquier servicio equivalente a EC2 de Amazon es válido (Ej: Virtual Machine Instance de Google Cloud)

2. La idea de la entrega esque ustedes mismos configuren el servidor para poder deployear su aplicación correctamente, así que utilizar algún PaaS no estaría permitido.
3. Sii, no hay problema. Solo les pedimos los otros porque son más fáciles de obtener.

**Comment by FarDust** [comment]
Muchas gracias. dejaré la Issue abierta un dia por si es de interés.
