### ISSUE TITLE
Problemas de cuenta Freenom

### ISSUE THREAD

**Issue by isipalma** [iic2173/2019-02#7]
Hola!

Estoy tratando de “comprar” un dominio en la página sugerida en el curso (Freenom), pero esta página no posee sistema de registro, y las demás opciones tampoco funcionan (entrar con google o facebook)

Qué recomiendan para solucionar esto? Que otra página podría ser útil para conseugir un dominio gratis?

Saludos y gracias de antemano

**Comment by nachocontreras** [comment]
Hola!

La página permite crear una cuenta al momento de registrar un dominio. Usa el siguiente link para hacerlo.

https://my.freenom.com/domains.php

Ahora, si se cae la página luego de realizar la orden de compra, te recomiendo iniciar sesión para ver si el dominio se registró correctamente (eso me pasó a mi).

Avisanos si te funcionó!

**Comment by isipalma** [comment]
Aun no me funciona

![FC81EA2F-45D7-4326-8E6C-B34C3BD0AEF0](https://user-images.githubusercontent.com/13772380/63695338-7a505000-c7e6-11e9-8bf4-e4e5058f1c7d.jpeg)

Cree que soy un robot jajaja. Y use un mail valido y todo.

**Comment by miguelramirezv** [comment]
Hola! Estoy teniendo el mismo problema ya por horas que me dice que no puede verificar que no sea un robot. Probé con varios mails y varios nombres de compañía, y aún así no me funciona. ¿Qué podría hacer?

**Comment by JorgeBdelaT** [comment]
@miguelramirezv nose si solucionaste tu problema, pero yo use name.com para tener un dominio. Con el pack estudiantil de github lo puedes obtener gratis!

**Comment by miguelramirezv** [comment]
Gracias!!
